language: go
sudo: false

# build code is from here: https://blog.questionable.services/article/build-go-binaries-travis-ci-github/
before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - go get -t -v ./...
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  - gox -os="linux darwin" -arch="amd64" -output="terraform-provider-k8s.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...


deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  file:
  - terraform-provider-k8s.linux.amd64
  - terraform-provider-k8s.darwin.amd64
  on:
    repo: melan/terraform-provider-k8s
    tags: true
